#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Bashmarks aliases
alias g="jump"
alias s="bookmark"
alias d="deletemark"
alias p="showmarks"
alias l="showmarks"

# Old bash aliases
#alias mysql='/usr/local/mysql/bin/mysql'
alias mysqladmin='/usr/local/mysql/bin/mysqladmin'
alias youtube-dl='youtube-dl -o "./%(title)s.%(ext)s" '
alias music-dl='youtube-dl --extract-audio --audio-format mp3'
# alias blender='/Applications/Blender\ 2.74/blender.app/Contents/MacOS/blender'
alias music-dl='youtube-dl --extract-audio --audio-format mp3'
alias upenv='source ~/.virtualenvs/logarhythm2.7/bin/activate'
alias linkenv='source ~/.virtualenvs/linkbeast3.4/bin/activate'
alias upqueue='celery -A logarhythm02project worker -l info'
alias hammer-time-npm='rm -rf node_modules && npm cache clear --force && npm i'

export PATH="/usr/local/bin/chromedriver:$PATH"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"
export EDITOR="/usr/bin/vim"
export MYVIMRC=~/.vimrc

export PATH="$PATH:$HOME/npm/bin"
export PATH="$PATH:$HOME/.node/bin"
export NODE_PATH=$HOME/.node/lib/node_modules
export NODE_PATH=$NODE_PATH:$HOME/.node/lib/node_modules
HOMEBREW_GITHUB_API_TOKEN="489deb6dba41cde63f828d866165ba45e98057a5"
export GOPATH="$HOME/golang"
export PATH="$PATH:$GOPATH/bin"
